export const VALIDATE_AMOUNT_COLUMNS = 'FILE_VALIDATOR/VALIDATE_AMOUNT_COLUMNS';
export const VALIDATE_AMOUNT_COLUMNS_FAILURE = 'FILE_VALIDATOR/VALIDATE_AMOUNT_COLUMNS_FAILURE';
export const VALIDATE_AMOUNT_COLUMNS_SUCCESS = 'FILE_VALIDATOR/VALIDATE_AMOUNT_COLUMNS_SUCCESS';

export const VALIDATE_COLUMN_COUNT = 'FILE_VALIDATOR/VALIDATE_COLUMN_COUNT';
export const VALIDATE_COLUMN_COUNT_FAILURE = 'FILE_VALIDATOR/VALIDATE_COLUMN_COUNT_FAILURE';
export const VALIDATE_COLUMN_COUNT_SUCCESS = 'FILE_VALIDATOR/VALIDATE_COLUMN_COUNT_SUCCESS';

export const VALIDATE_CURRENCY_COLUMNS = 'FILE_VALIDATOR/VALIDATE_CURRENCY_COLUMN';
export const VALIDATE_CURRENCY_COLUMNS_FAILURE = 'FILE_VALIDATOR/VALIDATE_CURRENCY_COLUMN_FAILURE';
export const VALIDATE_CURRENCY_COLUMNS_SUCCESS = 'FILE_VALIDATOR/VALIDATE_CURRENCY_COLUMN_SUCCESS';

export const VALIDATE_DATE_COLUMNS = 'FILE_VALIDATOR/VALIDATE_DATE_COLUMNS';
export const VALIDATE_DATE_COLUMNS_FAILURE = 'FILE_VALIDATOR/VALIDATE_DATE_COLUMNS_FAILURE';
export const VALIDATE_DATE_COLUMNS_SUCCESS = 'FILE_VALIDATOR/VALIDATE_DATE_COLUMNS_SUCCESS';
