export const VALIDATE_COLUMN_COUNT = 'FILE_VALIDATOR/VALIDATE_COLUMN_COUNT';
export const VALIDATE_COLUMN_COUNT_FAILURE = 'FILE_VALIDATOR/VALIDATE_COLUMN_COUNT_FAILURE';
export const VALIDATE_COLUMN_COUNT_SUCCESS = 'FILE_VALIDATOR/VALIDATE_COLUMN_COUNT_SUCCESS';
