export const EMPTY_ROWS_ANALYZE = 'PARSE_ROWS/EMPTY_ROWS_ANALYZE';
export const EMPTY_ROWS_ANALYZE_FAILURE = 'PARSE_ROWS/EMPTY_ROWS_ANALYZE_FAILURE';
export const EMPTY_ROWS_ANALYZE_SUCCESS = 'PARSE_ROWS/EMPTY_ROWS_ANALYZE_SUCCESS';

export const REMOVE_ROWS = 'PARSE_ROWS/REMOVE_ROWS';
export const REMOVE_ROWS_SUCCESS = 'PARSE_ROWS/REMOVE_ROWS_SUCCESS';

export const VERIFY_SUSPECTED_HEADER = 'PARSE_ROWS/VERIFY_SUSPECTED_HEADER';
