export const GUESS_CURRENCY_NAMES = 'TRANSFORM_CURRENCY_NAMES/GUESS_CURRENCY_NAMES';
export const GUESS_CURRENCY_NAMES_FAILURE = 'TRANSFORM_CURRENCY_NAMES/GUESS_CURRENCY_NAMES_FAILURE';
export const GUESS_CURRENCY_NAMES_SUCCESS = 'TRANSFORM_CURRENCY_NAMES/GUESS_CURRENCY_NAMES_SUCCESS';

export const TRANSFORM_CURRENCY_NAME = 'TRANSFORM_CURRENCY_NAMES/TRANSFORM_CURRENCY_NAME';
export const TRANSFORM_CURRENCY_NAME_FAILURE = 'TRANSFORM_CURRENCY_NAMES/TRANSFORM_CURRENCY_NAME_FAILURE';
export const TRANSFORM_CURRENCY_NAME_SUCCESS = 'TRANSFORM_CURRENCY_NAMES/TRANSFORM_CURRENCY_NAME_SUCCESS';
