export const FETCH_CURRENCIES = 'HOME/FETCH_CURRENCIES';
export const FETCH_CURRENCIES_FAILURE = 'HOME/FETCH_CURRENCIES_FAILURE';
export const FETCH_CURRENCIES_SUCCESS = 'HOME/FETCH_CURRENCIES_SUCCESS';

export const FETCH_RESULTS = 'HOME/FETCH_RESULTS';
export const FETCH_RESULTS_FAILURE = 'HOME/FETCH_RESULTS_FAILURE';
export const FETCH_RESULTS_SUCCESS = 'HOME/FETCH_RESULTS_SUCCESS';

export const UPDATE_REQUEST_URL = 'HOME/UPDATE_REQUEST_URL';
