export const FETCH_CURRENCIES = 'CURRENCY_SELECTOR/FETCH_CURRENCIES';
export const FETCH_CURRENCIES_FAILURE = 'CURRENCY_SELECTOR/FETCH_CURRENCIES_FAILURE';
export const FETCH_CURRENCIES_SUCCESS = 'CURRENCY_SELECTOR/FETCH_CURRENCIES_SUCCESS';

