export const PARSE_RESULTS = 'FILE_MANAGER/PARSE_RESULTS';
export const PARSE_RESULTS_FAILURE = 'FILE_MANAGER/PARSE_RESULTS_FAILURE';
export const PARSE_RESULTS_SUCCESS = 'FILE_MANAGER/PARSE_RESULTS_SUCCESS';

export const SELECT_FILE = 'PARSE_FILE/SELECT_FILE';
export const SELECT_FILE_FAILURE = 'FILE_MANAGER/SELECT_FILE_FAILURE';
export const SELECT_FILE_SUCCESS = 'FILE_MANAGER/SELECT_FILE_SUCCESS';

export const SET_STATIC_TO_CURRENCY = 'FILE_MANAGER/SET_STATIC_TO_CURRENCY';

export const UPDATE_PARSE_INDEXES = 'FILE_MANAGER/UPDATE_PARSE_INDEXES';
