export const UPDATE_EMAIL = 'SUBSCRIBE_TO_NEWSLETTER/UPDATE_EMAIL';

export const SUBSCRIBE_SUBMIT = 'SUBSCRIBE_TO_NEWSLETTER/SUBSCRIBE_SUBMIT';
export const SUBSCRIBE_SUBMIT_FAILURE = 'SUBSCRIBE_TO_NEWSLETTER/SUBSCRIBE_SUBMIT_FAILURE';
export const SUBSCRIBE_SUBMIT_SUCCESS = 'SUBSCRIBE_TO_NEWSLETTER/SUBSCRIBE_SUBMIT_SUCCESS';
